Repository inspec/inspec-azure, pull requests merged in 2021-09, with the labels that each got.

#449 skip nested nil values in array
  libraries/azure_backend.rb
Labels: bug

#451 Replace deprecated --without flag with bundle config
  .expeditor/buildkite/verify.sh
Labels: Expeditor: Skip All

#479 Fix YAML frontmatter lines in resource docs pages
  docs/resources/azure_ddos_protection_resource.md
  docs/resources/azure_ddos_protection_resources.md
  docs/resources/azure_dns_zones_resource.md
  docs/resources/azure_dns_zones_resources.md
  docs/resources/azure_policy_assignments.md
  docs/resources/azure_virtual_wan.md
Labels: Documentation

#432 Support migrate project solutions
  README.md
  docs/resources/azure_migrate_project_solution.md
  docs/resources/azure_migrate_project_solutions.md
  libraries/azure_migrate_project_solution.rb
  libraries/azure_migrate_project_solutions.rb
  test/integration/verify/controls/azure_migrate_project_solution.rb
  test/integration/verify/controls/azure_migrate_project_solutions.rb
  test/unit/resources/azure_migrate_project_solution_test.rb
  test/unit/resources/azure_migrate_project_solutions_test.rb
Labels: Version: Bump Minor, Documentation

#426 Support Azure Migrate Assessment Project (s)
  README.md
  docs/resources/azure_migrate_assessment_projects.md
  libraries/azure_migrate_assessment_project.rb
  libraries/azure_migrate_assessment_projects.rb
  test/integration/verify/controls/azure_migrate_assessment_project.rb
  test/integration/verify/controls/azure_migrate_assessment_projects.rb
  test/unit/resources/azure_migrate_assessment_project_test.rb
  test/unit/resources/azure_migrate_assessment_projects_test.rb
Labels: Version: Bump Minor, Documentation

#439 Support Azure Migrate Project Databases
  README.md
  docs/resources/azure_migrate_project_database.md
  docs/resources/azure_migrate_project_databases.md
  libraries/azure_migrate_project_database.rb
  libraries/azure_migrate_project_databases.rb
  test/integration/verify/controls/azure_migrate_project_database.rb
  test/integration/verify/controls/azure_migrate_project_databases.rb
  test/unit/resources/azure_migrate_project_database_test.rb
  test/unit/resources/azure_migrate_project_databases_test.rb
Labels: Version: Bump Minor, Documentation

#448 Support azure migrate project machines
  README.md
  docs/resources/azure_migrate_project_machine.md
  docs/resources/azure_migrate_project_machines.md
  libraries/azure_migrate_project_machine.rb
  libraries/azure_migrate_project_machines.rb
  test/integration/verify/controls/azure_migrate_project_machine.rb
  test/integration/verify/controls/azure_migrate_project_machines.rb
  test/unit/resources/azure_migrate_project_machine_test.rb
  test/unit/resources/azure_migrate_project_machines_test.rb
Labels: Version: Bump Minor, Documentation

#424 Support azure migrate assessments
  README.md
  docs/resources/azure_migrate_assessment.md
  docs/resources/azure_migrate_assessments.md
  libraries/azure_backend.rb
  libraries/azure_migrate_assessment.rb
  libraries/azure_migrate_assessments.rb
  terraform/azure.tf
  terraform/outputs.tf
  terraform/variables.tf
  test/integration/verify/controls/azure_migrate_assessment.rb
  test/integration/verify/controls/azure_migrate_assessments.rb
  test/unit/resources/azure_migrate_assessment_test.rb
  test/unit/resources/azure_migrate_assessments_test.rb
Labels: Version: Bump Minor, Documentation

#429 Support Azure Migrate Assessment Group(s)
  README.md
  docs/resources/azure_migrate_assessment_group.md
  docs/resources/azure_migrate_assessment_groups.md
  libraries/azure_migrate_assessment_group.rb
  libraries/azure_migrate_assessment_groups.rb
  test/integration/verify/controls/azure_migrate_assessment_group.rb
  test/integration/verify/controls/azure_migrate_assessment_groups.rb
  test/unit/resources/azure_migrate_assessment_group_test.rb
  test/unit/resources/azure_migrate_assessment_groups_test.rb
Labels: Version: Bump Minor, Documentation

#450 Support azure migrate project events
  README.md
  docs/resources/azure_migrate_project_event.md
  docs/resources/azure_migrate_project_events.md
  libraries/azure_migrate_project_event.rb
  libraries/azure_migrate_project_events.rb
  test/integration/verify/controls/azure_migrate_project_event.rb
  test/integration/verify/controls/azure_migrate_project_events.rb
  test/unit/resources/azure_migrate_project_event_test.rb
  test/unit/resources/azure_migrate_project_events_test.rb
Labels: Version: Bump Minor, Documentation

#486 doc minimum required role to run azure pack
  README.md
Labels: Documentation, CFT Support
