Repository inspec/inspec-azure, pull requests merged in 2021-07, with the labels that each got.

#408 adding storage account blob and table services
  docs/resources/azure_storage_account.md
  libraries/azure_storage_account.rb
Labels: Version: Bump Minor

#393 Support db migration service
  README.md
  docs/resources/azure_db_migration_service.md
  docs/resources/azure_db_migration_services.md
  libraries/azure_db_migration_service.rb
  libraries/azure_db_migration_services.rb
  terraform/azure.tf
  terraform/outputs.tf
  terraform/variables.tf
  test/integration/verify/controls/azure_db_migration_service.rb
  test/integration/verify/controls/azure_db_migration_services.rb
  test/unit/resources/azure_db_migration_service_test.rb
  test/unit/resources/azure_db_migration_services_test.rb
Labels: Documentation, Feature Request, Version: Bump Minor

#402 Support container groups
  README.md
  docs/resources/azure_container_group.md
  docs/resources/azure_container_groups.md
  libraries/azure_container_group.rb
  libraries/azure_container_groups.rb
  terraform/azure.tf
  terraform/outputs.tf
  terraform/variables.tf
  test/integration/verify/controls/azure_container_group.rb
  test/integration/verify/controls/azure_container_groups.rb
  test/unit/resources/azure_container_group_test.rb
  test/unit/resources/azure_container_groups_test.rb
Labels: Documentation, Version: Bump Minor
