Repository inspec/inspec-azure, pull requests merged in 2021-06, with the labels that each got.

#370 Support azure functions resource
  README.md
  docs/resources/azure_web_app_function.md
  docs/resources/azure_web_app_functions.md
  libraries/azure_web_app_function.rb
  libraries/azure_web_app_functions.rb
  terraform/azure.tf
  terraform/outputs.tf
  test/fixtures/functionapp.zip
  test/integration/verify/controls/azure_web_app_function.rb
  test/integration/verify/controls/azure_web_app_functions.rb
  test/unit/resources/azure_web_app_function_test.rb
  test/unit/resources/azure_web_app_functions_test.rb
Labels: Documentation, Version: Bump Minor, azure, ready

#375 Added Support for Azure Streaming Jobs function
  README.md
  docs/resources/azure_streaming_analytics_function.md
  docs/resources/azure_streaming_analytics_functions.md
  libraries/azure_streaming_analytic_function.rb
  libraries/azure_streaming_analytics_functions.rb
  terraform/azure.tf
  terraform/outputs.tf
  test/integration/verify/controls/azure_streaming_analytics_function_test.rb
  test/integration/verify/controls/azure_streaming_analytics_functions_test.rb
  test/unit/resources/azure_streaming_analytics_function.rb
  test/unit/resources/azure_streaming_analytics_functions.rb
Labels: Documentation, Feature Request, ready

#395 adding azure key vault extension
  docs/resources/azure_key_vault.md
  libraries/azure_key_vault.rb
Labels: Version: Bump Minor

#379 Add support for testing Azure Policy Assignments
  README.md
  docs/resources/azure_policy_assignments.md
  libraries/azure_policy_assignments.rb
  test/integration/verify/controls/azure_policy_assignments.rb
Labels: Documentation

#397 Extend policy definitions
  docs/resources/azure_policy_definitions.md
  libraries/azure_policy_definitions.rb
  test/integration/verify/controls/azure_policy_definitions.rb
Labels: Documentation, Version: Bump Minor

#399 Support policy exemptions
  README.md
  docs/resources/azure_policy_exemption.md
  docs/resources/azure_policy_exemptions.md
  libraries/azure_policy_exemption.rb
  libraries/azure_policy_exemptions.rb
  terraform/azure.tf
  terraform/outputs.tf
  test/integration/verify/controls/azure_policy_exemption.rb
  test/integration/verify/controls/azure_policy_exemptions.rb
  test/unit/resources/azure_policy_exemption_test.rb
  test/unit/resources/azure_policy_exemptions_test.rb
Labels: Documentation, Version: Bump Minor

#385 Support policy insights query result(s)
  README.md
  docs/resources/azure_policy_insights_query_result.md
  docs/resources/azure_policy_insights_query_results.md
  libraries/azure_backend.rb
  libraries/azure_generic_resources.rb
  libraries/azure_policy_insights_query_result.rb
  libraries/azure_policy_insights_query_results.rb
  terraform/azure.tf
  terraform/outputs.tf
  terraform/variables.tf
  test/integration/verify/controls/azure_policy_insights_query_result.rb
  test/integration/verify/controls/azure_policy_insights_query_results.rb
  test/unit/resources/azure_policy_insights_query_result_test.rb
  test/unit/resources/azure_policy_insights_query_results_test.rb
Labels: Documentation, Version: Bump Minor, ready

#403 Updating expeditor configuration
  .expeditor/config.yml
Labels: Expeditor: Skip All
