Repository inspec/inspec-azure, pull requests merged in 2021-11, with the labels that each got.

#530 Support azure vitual nw gateways
  docs/resources/azure_virtual_network_gateway.md
  libraries/azure_virtual_network_gateway.rb
Labels: Version: Bump Minor, Documentation, 2021_PQ4, CFT Support, ReadyForDocs

#537 Fix dates in release-dates.json
  docs-chef-io/static/release-notes/inspec-azure/release-dates.json
Labels: Documentation

#548 Minor docs fixes
  docs/resources/azure_policy_assignments.md
  docs/resources/azure_virtual_network_gateway_connections.md
Labels: Documentation

#434 Support migrate assessments machines
  README.md
  docs/resources/azure_migrate_assessment_machine.md
  docs/resources/azure_migrate_assessment_machines.md
  libraries/azure_migrate_assessment_machine.rb
  libraries/azure_migrate_assessment_machines.rb
  test/integration/verify/controls/azure_migrate_assessment_machine.rb
  test/integration/verify/controls/azure_migrate_assessment_machines.rb
  test/unit/resources/azure_migrate_assessment_machine_test.rb
  test/unit/resources/azure_migrate_assessment_machines_test.rb
Labels: Version: Bump Minor, Documentation, ReadyForDocs

#441 adding pipeline resource
  README.md
  docs/resources/azure_data_factory_pipeline.md
  docs/resources/azure_data_factory_pipelines.md
  libraries/azure_data_factory_pipeline.rb
  libraries/azure_data_factory_pipelines.rb
  terraform/azure.tf
  terraform/outputs.tf
  test/integration/verify/controls/azure_data_factory_pipeline.rb
  test/integration/verify/controls/azure_data_factory_pipelines.rb
  test/unit/resources/azure_data_factory_pipeline_test.rb
  test/unit/resources/azure_data_factory_pipelines_test.rb
Labels: Documentation, 2021_PQ4, ReadyForDocs

#443 Support azure migrate project
  README.md
  docs/resources/azure_migrate_project.md
  libraries/azure_migrate_project.rb
  test/integration/verify/controls/azure_migrate_project.rb
  test/unit/resources/azure_migrate_project_test.rb
Labels: Version: Bump Minor, Documentation, ReadyForDocs

#459 F/sentinel incidents
  README.md
  docs/resources/azure_sentinel_incidents_resource.md
  docs/resources/azure_sentinel_incidents_resources.md
  libraries/azure_sentinel_incidents_resource.rb
  libraries/azure_sentinel_incidents_resources.rb
  test/integration/verify/controls/azure_sentinel_incidents_resource.rb
  test/integration/verify/controls/azure_sentinel_incidents_resources.rb
  test/unit/resources/azure_sentinel_incidents_resource_test.rb
  test/unit/resources/azure_sentinel_incidents_resources_test.rb
Labels: Documentation, terraform-missing, 2021_PQ4, ReadyForDocs

#482 Support data lake storage gen2 filesystems
  README.md
  docs/resources/azure_data_lake_storage_gen2_filesystem.md
  docs/resources/azure_data_lake_storage_gen2_filesystems.md
  libraries/azure_data_lake_storage_gen2_filesystem.rb
  libraries/azure_data_lake_storage_gen2_filesystems.rb
  terraform/azure.tf
  terraform/outputs.tf
  terraform/variables.tf
  test/integration/verify/controls/azure_data_lake_storage_gen2_filesystem.rb
  test/integration/verify/controls/azure_data_lake_storage_gen2_filesystems.rb
  test/unit/resources/azure_data_lake_storage_gen2_filesystem_test.rb
  test/unit/resources/azure_data_lake_storage_gen2_filesystems_test.rb
Labels: Version: Bump Minor, Documentation, 2021_PQ4, ReadyForDocs

#517 Support power bi gateways
  README.md
  docs/resources/azure_power_bi_gateway.md
  docs/resources/azure_power_bi_gateways.md
  libraries/azure_power_bi_gateway.rb
  libraries/azure_power_bi_gateways.rb
  test/integration/verify/controls/azure_power_bi_gateway.rb
  test/integration/verify/controls/azure_power_bi_gateways.rb
  test/unit/resources/azure_power_bi_gateway_test.rb
  test/unit/resources/azure_power_bi_gateways_test.rb
Labels: Version: Bump Minor, Documentation, ReadyForDocs

#564 Removed broken type conversion in NSG resource
  libraries/azure_network_security_group.rb
Labels: Version: Bump Minor, CFT Support

#563 Support managed sql instance
  README.md
  docs/resources/azure_sql_managed_instance.md
  docs/resources/azure_sql_managed_instances.md
  libraries/azure_sql_managed_instance.rb
  libraries/azure_sql_managed_instances.rb
  terraform/azure.tf
  terraform/outputs.tf
  test/integration/verify/controls/azure_sql_managed_instance.rb
  test/integration/verify/controls/azure_sql_managed_instances.rb
  test/unit/resources/azure_sql_managed_instance_test.rb
  test/unit/resources/azure_sql_managed_instances_test.rb
Labels: Version: Bump Minor
