Repository inspec/inspec-azure, pull requests merged in 2021-08, with the labels that each got.

#407 azure data factory resource implementation : singular & plural resources
  README.md
  docs/resources/azure_data_factories.md
  docs/resources/azure_data_factory.md
  docs/resources/azure_express_route_providers.md
  libraries/azure_data_factories.rb
  libraries/azure_data_factory.rb
  libraries/azure_policy_insights_query_results.rb
  terraform/azure.tf
  terraform/outputs.tf
  test/integration/verify/controls/azure_data_factories.rb
  test/integration/verify/controls/azure_data_factory.rb
  test/unit/resources/azure_data_factories_test.rb
  test/unit/resources/azure_data_factory_test.rb
Labels: Documentation, Version: Bump Minor

#404 Support ad domain services
  README.md
  docs/resources/azure_active_directory_domain_service.md
  docs/resources/azure_active_directory_domain_services.md
  libraries/azure_active_directory_domain_service.rb
  libraries/azure_active_directory_domain_services.rb
  test/integration/verify/controls/azure_active_directory_domain_service.rb
  test/integration/verify/controls/azure_active_directory_domain_services.rb
  test/unit/resources/azure_active_directory_domain_service_test.rb
  test/unit/resources/azure_active_directory_domain_services_test.rb
Labels: Documentation, Version: Bump Minor

#413 Support resource health emerging issues
  README.md
  docs/resources/azure_resource_health_emerging_issue.md
  docs/resources/azure_resource_health_emerging_issues.md
  libraries/azure_resource_health_emerging_issue.rb
  libraries/azure_resource_health_emerging_issues.rb
  test/integration/verify/controls/azure_resource_health_emerging_issue.rb
  test/integration/verify/controls/azure_resource_health_emerging_issues.rb
  test/unit/resources/azure_resource_health_emerging_issue_test.rb
  test/unit/resources/azure_resource_health_emerging_issues_test.rb
Labels: Documentation, Version: Bump Minor

#411 Support resource health availability statuses
  README.md
  docs/resources/azure_resource_health_availability_status.md
  docs/resources/azure_resource_health_availability_statuses.md
  libraries/azure_resource_health_availability_status.rb
  libraries/azure_resource_health_availability_statuses.rb
  test/integration/verify/controls/azure_resource_health_availability_status.rb
  test/integration/verify/controls/azure_resource_health_availability_statuses.rb
  test/unit/resources/azure_resource_health_availability_status_test.rb
  test/unit/resources/azure_resource_health_availability_statuses_test.rb
Labels: Documentation, Version: Bump Minor

#406 Support ad directory objects
  docs/resources/azure_active_directory_object.md
  docs/resources/azure_active_directory_objects.md
  libraries/azure_active_directory_object.rb
  libraries/azure_active_directory_objects.rb
  terraform/outputs.tf
  terraform/variables.tf
  test/integration/verify/controls/azure_active_directory_object.rb
  test/integration/verify/controls/azure_active_directory_objects.rb
  test/unit/resources/azure_active_directory_object_test.rb
Labels: Version: Bump Minor, Documentation

#423 Account Storage Resource Fix
  libraries/azure_storage_account.rb
Labels: bug, Version: Bump Minor

#414 F/bastion hosts
  README.md
  docs/resources/azure_bastion_hosts_resource.md
  docs/resources/azure_bastion_hosts_resources.md
  libraries/azure_bastion_hosts_resource.rb
  libraries/azure_bastion_hosts_resources.rb
  terraform/azure.tf
  terraform/outputs.tf
  test/integration/verify/controls/azure_bastion_hosts_resource.rb
  test/integration/verify/controls/azure_bastion_hosts_resources.rb
  test/unit/resources/azure_bastion_hosts_resource_test.rb
  test/unit/resources/azure_bastion_hosts_resources_test.rb
Labels: Version: Bump Minor, Documentation

#394 Support azure redis cache
  README.md
  docs/resources/azure_redis_cache.md
  docs/resources/azure_redis_caches.md
  libraries/azure_redis_cache.rb
  libraries/azure_redis_caches.rb
  terraform/azure.tf
  terraform/outputs.tf
  terraform/variables.tf
  test/integration/verify/controls/azure_redis_cache.rb
  test/integration/verify/controls/azure_redis_caches.rb
  test/unit/resources/azure_redis_cache_test.rb
  test/unit/resources/azure_redis_caches_test.rb
Labels: Version: Bump Minor, Feature Request, Documentation

#416 F/azure dns
  README.md
  docs/resources/azure_dns_zones_resource.md
  docs/resources/azure_dns_zones_resources.md
  libraries/azure_dns_zones_resource.rb
  libraries/azure_dns_zones_resources.rb
  terraform/azure.tf
  terraform/outputs.tf
  test/integration/verify/controls/azure_dns_zones_resource.rb
  test/integration/verify/controls/azure_dns_zones_resources.rb
  test/unit/resources/azure_dns_zones_resource_test.rb
  test/unit/resources/azure_dns_zones_resources_test.rb
Labels: Version: Bump Minor, Documentation

#419 F/express route
  README.md
  docs/resources/azure_express_route_providers.md
  libraries/azure_express_route_providers.rb
  terraform/outputs.tf
  terraform/variables.tf
  test/integration/verify/controls/azure_express_route_providers.rb
  test/unit/resources/azure_express_route_providers_test.rb
Labels: Version: Bump Minor, Documentation

#431 Fix parameters in the azure_dns_zones_resource.md
  docs/resources/azure_dns_zones_resource.md
Labels: Documentation

#421 adding 'virtual network peering' resource
  README.md
  docs/resources/azure_virtual_network_peering.md
  docs/resources/azure_virtual_network_peerings.md
  libraries/azure_virtual_network_peering.rb
  libraries/azure_virtual_network_peerings.rb
  terraform/azure.tf
  terraform/outputs.tf
  test/integration/verify/controls/azurerm_virtual_network_peering.rb
  test/integration/verify/controls/azurerm_virtual_network_peerings.rb
  test/unit/resources/azure_virtual_network_peering_test.rb
  test/unit/resources/azure_virtual_network_peerings_test.rb
Labels: Version: Bump Minor, Documentation

#438 allow helper method for dynamic population of filter table from response
  libraries/azure_generic_resources.rb
Labels: enhancement, Version: Bump Minor

#420 F/express circuit route
  README.md
  docs/resources/azure_express_route_circuit.md
  docs/resources/azure_express_route_circuits.md
  libraries/azure_express_route_circuit.rb
  libraries/azure_express_route_circuits.rb
  terraform/azure.tf
  terraform/outputs.tf
  terraform/variables.tf
  test/integration/verify/controls/azure_express_route_circuit.rb
  test/integration/verify/controls/azure_express_route_circuits.rb
  test/unit/resources/azure_express_route_circuit_test.rb
  test/unit/resources/azure_express_route_circuits_test.rb
Labels: Version: Bump Minor, Documentation

#415 F/ddos protection
  README.md
  docs/resources/azure_ddos_protection_resource.md
  docs/resources/azure_ddos_protection_resources.md
  libraries/azure_ddos_protection_resource.rb
  libraries/azure_ddos_protection_resources.rb
  terraform/azure.tf
  terraform/outputs.tf
  test/integration/verify/controls/azure_ddos_protection_resource.rb
  test/integration/verify/controls/azure_ddos_protection_resources.rb
  test/unit/resources/azure_ddos_protection_resource_test.rb
  test/unit/resources/azure_ddos_protection_resources_test.rb
Labels: Version: Bump Minor, Documentation

#445 Fix docs errors in redis cache/s resources
  docs/resources/azure_redis_cache.md
  docs/resources/azure_redis_caches.md
Labels: Documentation

#417 Support virtual wans
  README.md
  docs/resources/azure_virtual_wan.md
  docs/resources/azure_virtual_wans.md
  libraries/azure_virtual_wan.rb
  libraries/azure_virtual_wans.rb
  terraform/azure.tf
  terraform/outputs.tf
  terraform/variables.tf
  test/integration/verify/controls/azure_virtual_wan.rb
  test/integration/verify/controls/azure_virtual_wans.rb
  test/unit/resources/azure_virtual_wan_test.rb
  test/unit/resources/azure_virtual_wans_test.rb
Labels: Version: Bump Minor, Documentation

#422 Support azure synapse notebooks
  README.md
  docs/resources/azure_synapse_notebook.md
  docs/resources/azure_synapse_notebooks.md
  libraries/azure_generic_resources.rb
  libraries/azure_synapse_notebook.rb
  libraries/azure_synapse_notebooks.rb
  test/integration/verify/controls/azure_synapse_notebook.rb
  test/integration/verify/controls/azure_synapse_notebooks.rb
  test/unit/resources/azure_synapse_notebook_test.rb
  test/unit/resources/azure_synapse_notebooks_test.rb
Labels: Version: Bump Minor, Documentation
