Repository inspec/inspec-azure, pull requests merged in 2022-03, with the labels that each got.

#487 RESOURCE-157 Support power bi embedded capacities
  docs-chef-io/content/inspec/resources/azure_power_bi_embedded_capacities.md
  docs-chef-io/content/inspec/resources/azure_power_bi_embedded_capacity.md
  libraries/azure_power_bi_embedded_capacities.rb
  libraries/azure_power_bi_embedded_capacity.rb
  terraform/azure.tf
  terraform/outputs.tf
  terraform/variables.tf
  test/integration/verify/controls/azure_power_bi_embedded_capacities.rb
  test/integration/verify/controls/azure_power_bi_embedded_capacity.rb
  test/unit/resources/azure_power_bi_embedded_capacities_test.rb
  test/unit/resources/azure_power_bi_embedded_capacity_test.rb
Labels: Version: Bump Minor, Documentation, ReadyForDocs

#521 RESOURCE-153 Support azure power bi app dashboards
  README.md
  docs-chef-io/content/inspec/resources/azure_power_bi_app_dashboard.md
  docs-chef-io/content/inspec/resources/azure_power_bi_app_dashboards.md
  libraries/azure_power_bi_app_dashboard.rb
  libraries/azure_power_bi_app_dashboards.rb
  test/integration/verify/controls/azure_power_bi_app_dashboard.rb
  test/integration/verify/controls/azure_power_bi_app_dashboards.rb
  test/unit/resources/azure_power_bi_app_dashboard_test.rb
  test/unit/resources/azure_power_bi_app_dashboards_test.rb
Labels: Version: Bump Minor, Documentation, ReadyForDocs

#529 RESOURCE-152 Support azure power bi app reports
  README.md
  docs-chef-io/content/inspec/resources/azure_power_bi_app_report.md
  docs-chef-io/content/inspec/resources/azure_power_bi_app_reports.md
  libraries/azure_power_bi_app_report.rb
  libraries/azure_power_bi_app_reports.rb
  test/integration/verify/controls/azure_power_bi_app_report.rb
  test/integration/verify/controls/azure_power_bi_app_reports.rb
  test/unit/resources/azure_power_bi_app_report_test.rb
  test/unit/resources/azure_power_bi_app_reports_test.rb
Labels: Version: Bump Minor, Documentation, ReadyForDocs

#534 RESOURCE-148 Support azure power bi capacity workloads
  README.md
  docs-chef-io/content/inspec/resources/azure_power_bi_capacity_workload.md
  docs-chef-io/content/inspec/resources/azure_power_bi_capacity_workloads.md
  libraries/azure_power_bi_capacity_workload.rb
  libraries/azure_power_bi_capacity_workloads.rb
  test/integration/verify/controls/azure_power_bi_capacity_workload.rb
  test/integration/verify/controls/azure_power_bi_capacity_workloads.rb
  test/unit/resources/azure_power_bi_capacity_workload_test.rb
  test/unit/resources/azure_power_bi_capacity_workloads_test.rb
Labels: Version: Bump Minor, Documentation, ReadyForDocs

#549 RESOURCE-145 Support azure power bi dataflow storage accounts
  README.md
  docs-chef-io/content/inspec/resources/azure_power_bi_dataflow_storage_accounts.md
  libraries/azure_power_bi_dataflow_storage_accounts.rb
  libraries/azure_power_bi_generic_resources.rb
  test/integration/verify/controls/azure_power_bi_dataflow_storage_accounts.rb
  test/unit/resources/azure_power_bi_dataflow_storage_accounts_test.rb
Labels: Version: Bump Minor, Documentation, ReadyForDocs

#562 RESOURCE-129 Support service bus namespaces
  README.md
  docs-chef-io/content/inspec/resources/azure_service_bus_namespace.md
  docs-chef-io/content/inspec/resources/azure_service_bus_namespaces.md
  libraries/azure_service_bus_namespace.rb
  libraries/azure_service_bus_namespaces.rb
  terraform/azure.tf
  terraform/outputs.tf
  test/integration/verify/controls/azure_service_bus_namespace.rb
  test/integration/verify/controls/azure_service_bus_namespaces.rb
  test/unit/resources/azure_service_bus_namespace_test.rb
  test/unit/resources/azure_service_bus_namespaces_test.rb
Labels: Version: Bump Minor, Documentation, ReadyForDocs

#565 RESOURCE-121 Support azure service bus topics
  README.md
  docs-chef-io/content/inspec/resources/azure_service_bus_topic.md
  docs-chef-io/content/inspec/resources/azure_service_bus_topics.md
  libraries/azure_service_bus_topic.rb
  libraries/azure_service_bus_topics.rb
  terraform/azure.tf
  terraform/outputs.tf
  test/integration/verify/controls/azure_service_bus_topic.rb
  test/integration/verify/controls/azure_service_bus_topics.rb
  test/unit/resources/azure_service_bus_topic_test.rb
  test/unit/resources/azure_service_bus_topics_test.rb
Labels: Version: Bump Minor, Documentation, ReadyForDocs

#567 RESOURCE-123 Support servicebus subscription rules
  README.md
  docs-chef-io/content/inspec/resources/azure_service_bus_subscription_rule.md
  docs-chef-io/content/inspec/resources/azure_service_bus_subscription_rules.md
  libraries/azure_service_bus_regions.rb
  libraries/azure_service_bus_subscription_rule.rb
  libraries/azure_service_bus_subscription_rules.rb
  terraform/azure.tf
  terraform/outputs.tf
  test/integration/verify/controls/azure_service_bus_regions.rb
  test/integration/verify/controls/azure_service_bus_subscription_rule.rb
  test/integration/verify/controls/azure_service_bus_subscription_rules.rb
  test/unit/resources/azure_service_bus_regions_test.rb
  test/unit/resources/azure_service_bus_subscription_rule_test.rb
  test/unit/resources/azure_service_bus_subscription_rules_test.rb
Labels: Version: Bump Minor, Documentation, ReadyForDocs

#568 RESOURCE-122 Support service bus subscriptions
  README.md
  docs-chef-io/content/inspec/resources/azure_service_bus_subscription.md
  docs-chef-io/content/inspec/resources/azure_service_bus_subscriptions.md
  libraries/azure_service_bus_subscription.rb
  libraries/azure_service_bus_subscriptions.rb
  test/integration/verify/controls/azure_service_bus_subscription.rb
  test/integration/verify/controls/azure_service_bus_subscriptions.rb
  test/unit/resources/azure_service_bus_subscription_test.rb
  test/unit/resources/azure_service_bus_subscriptions_test.rb
Labels: Version: Bump Minor, Documentation, ReadyForDocs

#566 RESOURCE-124 Support service bus regions
  README.md
  docs-chef-io/content/inspec/resources/azure_service_bus_regions.md
Labels: Version: Bump Minor, Documentation, ReadyForDocs

#575 RESOURCE-132 Support managed applications
  README.md
  docs-chef-io/content/inspec/resources/azure_managed_application.md
  docs-chef-io/content/inspec/resources/azure_managed_applications.md
  libraries/azure_managed_application.rb
  libraries/azure_managed_applications.rb
  terraform/azure.tf
  terraform/outputs.tf
  test/integration/verify/controls/azure_managed_application.rb
  test/integration/verify/controls/azure_managed_applications.rb
  test/unit/resources/azure_managed_application_test.rb
  test/unit/resources/azure_managed_applications_test.rb
Labels: Version: Bump Minor, Documentation, ReadyForDocs

#578 RESOURCE-118 Support azure service fabric mesh apps
  README.md
  docs-chef-io/content/inspec/resources/azure_service_fabric_mesh_application.md
  docs-chef-io/content/inspec/resources/azure_service_fabric_mesh_applications.md
  libraries/azure_service_fabric_mesh_application.rb
  libraries/azure_service_fabric_mesh_applications.rb
  test/integration/verify/controls/azure_service_fabric_mesh_application.rb
  test/integration/verify/controls/azure_service_fabric_mesh_applications.rb
  test/unit/resources/azure_service_fabric_mesh_application_test.rb
  test/unit/resources/azure_service_fabric_mesh_applications_test.rb
Labels: Version: Bump Minor, Documentation, ReadyForDocs

#581 RESOURCE-114 Support azure service fabric mesh volumes
  README.md
  docs-chef-io/content/inspec/resources/azure_service_fabric_mesh_volume.md
  docs-chef-io/content/inspec/resources/azure_service_fabric_mesh_volumes.md
  libraries/azure_service_fabric_mesh_volume.rb
  libraries/azure_service_fabric_mesh_volumes.rb
  test/integration/verify/controls/azure_service_fabric_mesh_volume.rb
  test/integration/verify/controls/azure_service_fabric_mesh_volumes.rb
  test/unit/resources/azure_service_fabric_mesh_volume_test.rb
  test/unit/resources/azure_service_fabric_mesh_volumes_test.rb
Labels: Version: Bump Minor, Documentation, ReadyForDocs

#580 RESOURCE-116 Support azure service fabric mesh service replicas
  README.md
  docs-chef-io/content/inspec/resources/azure_service_fabric_mesh_replica.md
  docs-chef-io/content/inspec/resources/azure_service_fabric_mesh_replicas.md
  libraries/azure_service_fabric_mesh_replica.rb
  libraries/azure_service_fabric_mesh_replicas.rb
  test/integration/verify/controls/azure_service_fabric_mesh_replica.rb
  test/integration/verify/controls/azure_service_fabric_mesh_replicas.rb
  test/unit/resources/azure_service_fabric_mesh_replica_test.rb
  test/unit/resources/azure_service_fabric_mesh_replicas_test.rb
Labels: Version: Bump Minor, Documentation, ReadyForDocs

#579 RESOURCE-117 Support azure service fabric mesh service
  README.md
  docs-chef-io/content/inspec/resources/azure_service_fabric_mesh_service.md
  docs-chef-io/content/inspec/resources/azure_service_fabric_mesh_services.md
  libraries/azure_service_fabric_mesh_service.rb
  libraries/azure_service_fabric_mesh_services.rb
  test/integration/verify/controls/azure_service_fabric_mesh_service.rb
  test/integration/verify/controls/azure_service_fabric_mesh_services.rb
  test/unit/resources/azure_service_fabric_mesh_service_test.rb
  test/unit/resources/azure_service_fabric_mesh_services_test.rb
Labels: Version: Bump Minor, Documentation, ReadyForDocs

#582 RESOURCE-115 Support azure service fabric mesh network
  README.md
  docs-chef-io/content/inspec/resources/azure_service_fabric_mesh_network.md
  docs-chef-io/content/inspec/resources/azure_service_fabric_mesh_networks.md
  libraries/azure_service_fabric_mesh_network.rb
  libraries/azure_service_fabric_mesh_networks.rb
  test/integration/verify/controls/azure_service_fabric_mesh_network.rb
  test/integration/verify/controls/azure_service_fabric_mesh_networks.rb
  test/unit/resources/azure_service_fabric_mesh_network_test.rb
  test/unit/resources/azure_service_fabric_mesh_networks_test.rb
Labels: Version: Bump Minor, Documentation, ReadyForDocs

#601 RESOURCE-103 Support azure synapse workspaces
  README.md
  docs-chef-io/content/inspec/resources/azure_synapse_workspace.md
  docs-chef-io/content/inspec/resources/azure_synapse_workspaces.md
  libraries/azure_synapse_workspace.rb
  libraries/azure_synapse_workspaces.rb
  terraform/azure.tf
  terraform/outputs.tf
  test/integration/verify/controls/azure_synapse_workspace.rb
  test/integration/verify/controls/azure_synapse_workspaces.rb
  test/unit/resources/azure_synapse_workspace_test.rb
  test/unit/resources/azure_synapse_workspaces_test.rb
Labels: Version: Bump Minor, Documentation, ReadyForDocs

#647 Update docs makefile
  docs-chef-io/Makefile
  docs-chef-io/netlify.toml
Labels: Documentation

#648 Adding storage account logging features
  libraries/azure_storage_account.rb
Labels: Version: Bump Minor
