Repository inspec/inspec-azure, pull requests merged in 2022-02, with the labels that each got.

#624 Support caching of azure nw sgs
  docs/resources/azure_network_security_group.md
  docs/resources/azure_network_security_groups.md
  libraries/azure_generic_resource.rb
  libraries/azure_network_security_group.rb
  libraries/azure_network_security_groups.rb
  libraries/backend/helpers.rb
Labels: Version: Bump Minor, Documentation, CFT Support, ReadyForDocs

#628 Support cache for storage accounts
  docs/resources/azure_storage_account.md
  docs/resources/azure_storage_accounts.md
  libraries/azure_storage_account.rb
  libraries/azure_storage_accounts.rb
Labels: Version: Bump Minor, Documentation, CFT Support, ReadyForDocs

#608 stick active support to older versions for ruby < 2.7
  .expeditor/buildkite/verify.sh
  .expeditor/verify.pipeline.yml
  Gemfile
  libraries/azure_generic_resource.rb
  libraries/azure_network_security_group.rb
  libraries/backend/azure_require.rb
Labels: Version: Skip Bump

#514 RESOURCE-134 F/pipeline runs
  README.md
  docs/resources/azure_data_factory_pipeline_run_resource.md
  docs/resources/azure_data_factory_pipeline_run_resources.md
  libraries/azure_data_factory_pipeline_run_resource.rb
  libraries/azure_data_factory_pipeline_run_resources.rb
  test/integration/verify/controls/azure_data_factory_linked_services.rb
  test/unit/resources/azure_data_factory_pipeline_run_resource.rb
  test/unit/resources/azure_data_factory_pipeline_run_resources.rb
Labels: Feature Request, Documentation, terraform-missing, 2021_PQ4, ReadyForDocs

#528 RESOURCE-151 Support azure power bi app dashboard tiles
  README.md
  docs/resources/azure_power_bi_app_dashboard_tile.md
  docs/resources/azure_power_bi_app_dashboard_tiles.md
  libraries/azure_power_bi_app_dashboard_tile.rb
  libraries/azure_power_bi_app_dashboard_tiles.rb
  test/integration/verify/controls/azure_power_bi_app_dashboard_tile.rb
  test/integration/verify/controls/azure_power_bi_app_dashboard_tiles.rb
  test/unit/resources/azure_power_bi_app_dashboard_tile_test.rb
  test/unit/resources/azure_power_bi_app_dashboard_tiles_test.rb
Labels: Version: Bump Minor, Documentation, ReadyForDocs

#532 RESOURCE-150 Support power bi capacities
  README.md
  docs/resources/azure_power_bi_capacities.md
  libraries/azure_power_bi_capacities.rb
  test/integration/verify/controls/azure_power_bi_capacities.rb
  test/unit/resources/azure_power_bi_capacities_test.rb
Labels: Version: Bump Minor, Documentation, ReadyForDocs

#533 RESOURCE-149 Support azure power bi capacity refreshables
  README.md
  docs/resources/azure_power_bi_capacity_refreshable.md
  docs/resources/azure_power_bi_capacity_refreshables.md
  libraries/azure_power_bi_capacity_refreshable.rb
  libraries/azure_power_bi_capacity_refreshables.rb
  test/integration/verify/controls/azure_power_bi_capacity_refreshable.rb
  test/integration/verify/controls/azure_power_bi_capacity_refreshables.rb
  test/unit/resources/azure_power_bi_capacity_refreshable_test.rb
  test/unit/resources/azure_power_bi_capacity_refreshables_test.rb
Labels: Version: Bump Minor, Documentation, ReadyForDocs

#535 RESOURCE-142 Support power bi dataflows
  README.md
  docs/resources/azure_power_bi_dataflow.md
  docs/resources/azure_power_bi_dataflows.md
  libraries/azure_power_bi_dataflow.rb
  libraries/azure_power_bi_dataflows.rb
  test/integration/verify/controls/azure_power_bi_dataflow.rb
  test/integration/verify/controls/azure_power_bi_dataflows.rb
  test/unit/resources/azure_power_bi_dataflow_test.rb
  test/unit/resources/azure_power_bi_dataflows_test.rb
Labels: Version: Bump Minor, Documentation, 2021_PQ4, ReadyForDocs

#536 RESOURCE-141 Support azure power bi datasets
  README.md
  docs/resources/azure_power_bi_dataset.md
  docs/resources/azure_power_bi_datasets.md
  libraries/azure_power_bi_dataset.rb
  libraries/azure_power_bi_datasets.rb
  test/integration/verify/controls/azure_power_bi_dataset.rb
  test/integration/verify/controls/azure_power_bi_datasets.rb
  test/unit/resources/azure_power_bi_dataset_test.rb
  test/unit/resources/azure_power_bi_datasets_test.rb
Labels: Version: Bump Minor, Documentation, 2021_PQ4, ReadyForDocs

#594 RESOURCE-111 Support sql vms
  README.md
  docs/resources/azure_sql_virtual_machine.md
  docs/resources/azure_sql_virtual_machines.md
  libraries/azure_sql_virtual_machine.rb
  libraries/azure_sql_virtual_machines.rb
  terraform/azure.tf
  terraform/outputs.tf
  test/integration/verify/controls/azure_sql_virtual_machine.rb
  test/integration/verify/controls/azure_sql_virtual_machines.rb
  test/unit/resources/azure_sql_virtual_machine_test.rb
  test/unit/resources/azure_sql_virtual_machines_test.rb
Labels: Documentation, ReadyForDocs

#596 RESOURCE-110 Support availability group listeners sql vm
  README.md
  docs/resources/azure_sql_virtual_machine_group_availability_listener.md
  docs/resources/azure_sql_virtual_machine_group_availability_listeners.md
  libraries/azure_sql_virtual_machine_group_availability_listener.rb
  libraries/azure_sql_virtual_machine_group_availability_listeners.rb
  test/integration/verify/controls/azure_sql_virtual_machine_group_availability_listener.rb
  test/integration/verify/controls/azure_sql_virtual_machine_group_availability_listeners.rb
  test/unit/resources/azure_sql_virtual_machine_group_availability_listener_test.rb
  test/unit/resources/azure_sql_virtual_machine_group_availability_listeners_test.rb
Labels: Documentation, ReadyForDocs

#595 RESOURCE-109 Support sql vm groups
  README.md
  docs/resources/azure_sql_virtual_machine_group.md
  docs/resources/azure_sql_virtual_machine_groups.md
  libraries/azure_sql_virtual_machine_group.rb
  libraries/azure_sql_virtual_machine_groups.rb
  test/integration/verify/controls/azure_sql_virtual_machine_group.rb
  test/integration/verify/controls/azure_sql_virtual_machine_groups.rb
  test/unit/resources/azure_sql_virtual_machine_group_test.rb
  test/unit/resources/azure_sql_virtual_machine_groups_test.rb
Labels: Documentation, ReadyForDocs

#440 Support azure migrate db instances
  README.md
  docs-chef-io/content/inspec/resources/azure_migrate_project_database_instance.md
  docs-chef-io/content/inspec/resources/azure_migrate_project_database_instances.md
  libraries/azure_migrate_project_database_instance.rb
  libraries/azure_migrate_project_database_instances.rb
  test/integration/verify/controls/azure_migrate_project_database_instance.rb
  test/integration/verify/controls/azure_migrate_project_database_instances.rb
  test/integration/verify/controls/azure_virtual_network_gateway.rb
  test/unit/resources/azure_migrate_project_database_instance_test.rb
  test/unit/resources/azure_migrate_project_database_instances_test.rb
Labels: Version: Bump Minor, Documentation

#507 RESOURCE-144 Support power bi dashboards
  README.md
  docs-chef-io/content/inspec/resources/azure_power_bi_dashboard.md
  docs-chef-io/content/inspec/resources/azure_power_bi_dashboards.md
  libraries/azure_power_bi_dashboard.rb
  libraries/azure_power_bi_dashboards.rb
  terraform/azure.tf
  terraform/outputs.tf
  test/integration/verify/controls/azure_power_bi_dashboard.rb
  test/integration/verify/controls/azure_power_bi_dashboards.rb
  test/unit/resources/azure_power_bi_dashboard_test.rb
  test/unit/resources/azure_power_bi_dashboards_test.rb
Labels: Version: Bump Minor, Documentation, ReadyForDocs

#506 RESOURCE-136 F/df ds
  README.md
  docs-chef-io/content/inspec/resources/azure_data_factory_dataset.md
  docs-chef-io/content/inspec/resources/azure_data_factory_datasets.md
  libraries/azure_data_factory_dataset.rb
  libraries/azure_data_factory_datasets.rb
  terraform/azure.tf
  terraform/variables.tf
  test/integration/verify/controls/azure_data_factory_dataset.rb
  test/integration/verify/controls/azure_data_factory_datasets.rb
  test/unit/resources/azure_data_factory_dataset_test.rb
  test/unit/resources/azure_data_factory_datasets_test.rb
Labels: Documentation, 2021_PQ4, ReadyForDocs

#516 RESOURCE-143 Support power bi dashboard tiles
  docs-chef-io/content/inspec/resources/azure_power_bi_dashboard.md
  docs-chef-io/content/inspec/resources/azure_power_bi_dashboard_tile.md
  docs-chef-io/content/inspec/resources/azure_power_bi_dashboard_tiles.md
  docs-chef-io/content/inspec/resources/azure_power_bi_dashboards.md
  libraries/azure_power_bi_dashboard_tile.rb
  libraries/azure_power_bi_dashboard_tiles.rb
  test/integration/verify/controls/azure_power_bi_dashboard_tile.rb
  test/integration/verify/controls/azure_power_bi_dashboard_tiles.rb
  test/unit/resources/azure_power_bi_dashboard_tile_test.rb
  test/unit/resources/azure_power_bi_dashboard_tiles_test.rb
Labels: Version: Bump Minor, Documentation, ReadyForDocs

#538 RESOURCE-140 Support Azure Power BI dataset datasources
  README.md
  docs-chef-io/content/inspec/resources/azure_power_bi_dataset_datasources.md
  libraries/azure_power_bi_dataset_datasources.rb
  test/integration/verify/controls/azure_power_bi_dataset_datasources.rb
  test/unit/resources/azure_power_bi_dataset_datasources_test.rb
Labels: Version: Bump Minor, Documentation, 2021_PQ4, ReadyForDocs

#485 RESOURCE-139 Support adls paths
  docs-chef-io/content/inspec/resources/azure_data_lake_storage_gen2_path.md
  docs-chef-io/content/inspec/resources/azure_data_lake_storage_gen2_paths.md
  libraries/azure_data_lake_storage_gen2_path.rb
  libraries/azure_data_lake_storage_gen2_paths.rb
  terraform/azure.tf
  terraform/outputs.tf
  terraform/variables.tf
  test/integration/verify/controls/azure_data_lake_storage_gen2_path.rb
  test/integration/verify/controls/azure_data_lake_storage_gen2_paths.rb
  test/unit/resources/azure_data_lake_storage_gen2_path_test.rb
  test/unit/resources/azure_data_lake_storage_gen2_paths_test.rb
Labels: Version: Bump Minor, Documentation, 2021_PQ4, ReadyForDocs
